/**
 * SoluStock reliable synchronization protocol.
 *
 * Design goals:
 * - Stable, immutable document ids across all peers.
 * - Idempotent operations so retries never create duplicates.
 * - Monotonic sequence-based change log for missed-change recovery.
 * - Explicit conflict detection with user resolution.
 */

export type SyncMethod = 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface SyncOperationPayload {
  /** Globally unique operation id generated by the originating peer. */
  operationId: string;
  /** Stable document id. Must never change. */
  documentId: string;
  /** Logical collection name from SYNC_COLLECTIONS. */
  collection: string;
  /** HTTP-style method describing the mutation. */
  method: SyncMethod;
  /** Server sequence number the peer knew at the time of the change. */
  baseSequence?: number;
  /** Server updatedAt the peer knew at the time of the change. */
  baseUpdatedAt?: string;
  /** Full document payload for POST/PUT or partial payload for PATCH. */
  body?: any;
  /** Original API path (legacy / debugging). */
  path?: string;
}

export interface SyncPushRequest {
  operations: SyncOperationPayload[];
}

export type SyncPushResultStatus = 'applied' | 'duplicate' | 'conflict' | 'missing' | 'error';

export interface SyncPushResult {
  operationId: string;
  status: SyncPushResultStatus;
  /** New server sequence number assigned to this change. */
  sequence?: number;
  /** Current server document snapshot (for applied/duplicate/conflict). */
  doc?: any;
  /** Conflict details when status === 'conflict'. */
  conflict?: {
    remoteDoc: any;
    message: string;
  };
  error?: string;
}

export interface SyncPushResponse {
  results: SyncPushResult[];
  /** Highest sequence number known by the server. */
  maxSequence: number;
}

export interface SyncPullRequest {
  /** Per-collection cursor. 0 means "beginning of time". */
  cursor: number;
  limit?: number;
}

export interface SyncPullResponse {
  docs: any[];
  hasMore: boolean;
  /** Highest sequence number known by the server for this collection. */
  maxSequence: number;
  /** Cursor value to send next to receive the following page. */
  nextCursor: number;
}

export interface SyncChangeNotification {
  collection: string;
  documentId: string;
  operation: 'create' | 'update' | 'delete';
  sequence: number;
}

export interface SyncBatchNotification {
  topic: 'sync:change';
  /** Highest global sequence number at the time of the batch. */
  maxSequence: number;
  /** Changed collections with their newest sequence. */
  changes: SyncChangeNotification[];
  /** Originating client id, if the change came from a client. */
  sourceClientId?: string;
}

export interface SyncCursorState {
  [collection: string]: number;
}
