/**
 * Generates src/renderer/src/config/wilayas.ts (69 wilayas + their daïras +
 * baladiyas/communes) from the "Algeria Cities 2026" dataset
 * (Law 26-06, April 4, 2026).
 *
 * Usage:
 *   node scripts/generate-wilayas.cjs [path-to-algeria_cities.json]
 *
 * Default dataset path: %TEMP%/opencode/algeria-data/algeria_cities.json
 */
const fs = require('fs');
const path = require('path');

const datasetPath = process.argv[2] || path.join(process.env.TEMP || '', 'opencode', 'algeria-data', 'algeria_cities.json');
const outFile = path.join(__dirname, '..', 'src', 'renderer', 'src', 'config', 'wilayas.ts');

const rows = JSON.parse(fs.readFileSync(datasetPath, 'utf8'));

const wilayaMap = new Map();
for (const r of rows) {
  const code = String(r.wilaya_code).padStart(2, '0');
  if (!wilayaMap.has(code)) {
    wilayaMap.set(code, {
      code,
      fr: String(r.wilaya_name_fr).trim(),
      ar: String(r.wilaya_name).trim(),
      lat: Number(r.Lat),
      lng: Number(r.Long),
      dairas: new Map(),
      baladiyas: new Map(),
    });
  }
  const dairaFr = String(r.daira_name_fr).trim();
  const dairaAr = String(r.daira_name).trim();
  const baladiyaFr = String(r.commune_name_fr).trim();
  const baladiyaAr = String(r.commune_name).trim();
  const w = wilayaMap.get(code);
  if (!w.dairas.has(dairaFr)) w.dairas.set(dairaFr, dairaAr);
  if (!w.baladiyas.has(baladiyaFr)) w.baladiyas.set(baladiyaFr, baladiyaAr);
}

// Stable ordering by wilaya code (001 -> 069)
const wilayas = [...wilayaMap.values()].sort((a, b) => a.code.localeCompare(b.code));

const q = JSON.stringify;
const esc = (s) => q(s);

const lines = [];
lines.push(`// Alembic: 69 wilayas + daïras + baladiyas (communes) (Law N° 26-06, April 4, 2026, JO N° 25)`);
lines.push(`// Generated by scripts/generate-wilayas.cjs from the "Algeria Cities 2026" dataset.`);
lines.push(`// Source: https://github.com/ihahachi/Algeria-Cities`);
lines.push(``);
lines.push(`export interface Daira {`);
lines.push(`  fr: string`);
lines.push(`  ar: string`);
lines.push(`}`);
lines.push(``);
lines.push(`export type Baladiya = Daira;`);
lines.push(``);
lines.push(`export interface Wilaya {`);
lines.push(`  code: string`);
lines.push(`  fr: string`);
lines.push(`  ar: string`);
lines.push(`  lat?: number`);
lines.push(`  lng?: number`);
lines.push(`  dairas: Daira[]`);
lines.push(`  baladiyas: Baladiya[]`);
lines.push(`}`);
lines.push(``);
lines.push(`export const WILAYAS: Wilaya[] = [`);
for (const w of wilayas) {
  lines.push(`  {`);
  lines.push(`    code: ${esc(w.code)},`);
  lines.push(`    fr: ${esc(w.fr)},`);
  lines.push(`    ar: ${esc(w.ar)},`);
  if (w.lat != null && w.lng != null) {
    lines.push(`    lat: ${w.lat},`);
    lines.push(`    lng: ${w.lng},`);
  }
  const dairas = [...w.dairas.entries()]
    .map(([fr, ar]) => ({ fr, ar }))
    .sort((a, b) => a.fr.localeCompare(b.fr, 'fr'));
  lines.push(`    dairas: [`);
  for (const d of dairas) {
    lines.push(`      { fr: ${esc(d.fr)}, ar: ${esc(d.ar)} },`);
  }
  lines.push(`    ],`);
  const baladiyas = [...w.baladiyas.entries()]
    .map(([fr, ar]) => ({ fr, ar }))
    .sort((a, b) => a.fr.localeCompare(b.fr, 'fr'));
  lines.push(`    baladiyas: [`);
  for (const b of baladiyas) {
    lines.push(`      { fr: ${esc(b.fr)}, ar: ${esc(b.ar)} },`);
  }
  lines.push(`    ],`);
  lines.push(`  },`);
}
lines.push(`];`);
lines.push(``);
lines.push(`export const wilayaOptions = (lang: string) =>`);
lines.push(`  WILAYAS.map((w) => ({`);
lines.push(`    value: w.code,`);
lines.push(`    label: \`\${w.code} - \${lang === 'ar' ? w.ar : w.fr}\`,`);
lines.push(`  }))`);
lines.push(``);
lines.push(`export const getDairasForWilaya = (wilayaCode?: string) => {`);
lines.push(`  if (!wilayaCode) return []`);
lines.push(`  const w = WILAYAS.find((x) => x.code === wilayaCode || x.fr === wilayaCode || x.ar === wilayaCode)`);
lines.push(`  return w?.dairas ?? []`);
lines.push(`}`);
lines.push(``);
lines.push(`export const dairaOptions = (wilayaCode: string, lang: string) =>`);
lines.push(`  getDairasForWilaya(wilayaCode).map((d) => ({`);
lines.push(`    value: d.fr,`);
lines.push(`    label: lang === 'ar' ? d.ar : d.fr,`);
lines.push(`  }))`);
lines.push(``);
lines.push(`export const getBaladiyasForWilaya = (wilayaCode?: string) => {`);
lines.push(`  if (!wilayaCode) return []`);
lines.push(`  const w = WILAYAS.find((x) => x.code === wilayaCode || x.fr === wilayaCode || x.ar === wilayaCode)`);
lines.push(`  return w?.baladiyas ?? []`);
lines.push(`}`);
lines.push(``);
lines.push(`export const baladiyaOptions = (wilayaCode: string, lang: string) =>`);
lines.push(`  getBaladiyasForWilaya(wilayaCode).map((b) => ({`);
lines.push(`    value: b.fr,`);
lines.push(`    label: lang === 'ar' ? b.ar : b.fr,`);
lines.push(`  }))`);
lines.push(``);
lines.push(`export const getWilayaLabel = (value?: string, lang = '') => {`);
lines.push(`  if (!value) return '-'`);
lines.push(`  const match = WILAYAS.find((w) => w.code === value || w.fr.toLowerCase() === value.toLowerCase() || w.ar === value)`);
lines.push(`  if (!match) return value`);
lines.push(`  const label = lang === 'ar' ? match.ar : match.fr`);
lines.push(`  return \`\${match.code} - \${label}\``);
lines.push(`}`);
lines.push(``);
lines.push(`export const getDairaLabel = (wilayaCode?: string, value?: string, lang = '') => {`);
lines.push(`  if (!value) return '-'`);
lines.push(`  const daira = getDairasForWilaya(wilayaCode).find((d) => d.fr === value || d.ar === value)`);
lines.push(`  if (!daira) return value`);
lines.push(`  return lang === 'ar' ? daira.ar : daira.fr`);
lines.push(`}`);
lines.push(``);
lines.push(`export const getBaladiyaLabel = (wilayaCode?: string, value?: string, lang = '') => {`);
lines.push(`  if (!value) return '-'`);
lines.push(`  const baladiya = getBaladiyasForWilaya(wilayaCode).find((b) => b.fr === value || b.ar === value)`);
lines.push(`  if (!baladiya) return value`);
lines.push(`  return lang === 'ar' ? baladiya.ar : baladiya.fr`);
lines.push(`}`);
lines.push(``);

const content = lines.join('\n');
fs.writeFileSync(outFile, content, 'utf8');
console.log(`Wrote ${outFile} (${wilayas.length} wilayas, ${wilayas.reduce((sum, w) => sum + w.dairas.size, 0)} daïras, ${wilayas.reduce((sum, w) => sum + w.baladiyas.size, 0)} baladiyas)`);